### ISSUE TITLE
About the splits of train/val/test

### ISSUE THREAD

**Issue by Luxuff** [Lingzhi-WANG/Quotation-Recommendation#1]
Hi, thank you for your work. I was wondering how to split the dataset (which is https://github.com/Lingzhi-WANG/Datasets-for-Quotation-Recommendation) into **train.json, test.json and valid.json**. And how do you generate the '_quote_3dicts.json' in your code for the two of them. Could you please share the scripts?
Looking forward to your reply.

**Comment by Lingzhi-WANG** [comment]
Thanks for your question. You can randomly split the datasets into 80%, 10%, and 10%, for training, valid and test. We only used the self.quote_dic from "_quote_3dicts.json". The self.quote_dic is a simple dictionary, where the key is "the string of quotation" and the value is its label. For example, 

{"History will have to record that the greatest tragedy of this period of social transition was not the strident clamor of the bad people, but the appalling silence of the good people.": 998, "It's not that I'm so smart, it's just that I stay with problems longer.": 603, "Perfection is not attainable, but if we chase perfection we can catch excellence.": 909, "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.": 270, ...}

If you have any more questions, feel free to propose.

**Comment by Luxuff** [comment]
Thank you for your reply. I now know how to generate the train/val/test data, which I found in your another paper( Continuity of Topic, Interaction, and Query: Learning to Quote in Online Conversations) by afternoon, but for that example you mentioned, I'm still confused. I didn't found any data like "quotation string: label", does this mean that the dataset(https://github.com/Lingzhi-WANG/Datasets-for-Quotation-Recommendation) is a processed one? or you label the data manually?  I'm new to this field, sorry for my amateur questions.

**Comment by Lingzhi-WANG** [comment]
The label is to identify a quotation, which also means the label is not made manually. You can assign any unique label or index for each quotation.

**Comment by Luxuff** [comment]
I see, thank you! That really help me a lot.
